In [1]:
import torch

/Users/gimchangheon/opt/anaconda3/envs/dl-challenge/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
def _get_D_No_Mask(self, sequence_length, image_patches_length):
    n = torch.arange(sequence_length).unsqueeze(1) # 
    m = torch.arange(image_patches_length).unsqueeze(0)
    denominator = m/n
    # Broadcast self.gamma ** (n - m) with appropriate masking to set values where n < m to 0
    D = (self.gamma ** (abs(n - m) // denominator) ) .float() # BiRetention
    # fill the NaN with 0
    D[D != D] = 0
    return D
def _get_D_No_Mask(self, sequence_length, image_patches_length):
    n = torch.arange(sequence_length).unsqueeze(1)
    Xm = torch.arrange(7)
    Ym = torch.arrange(105)
    denominator = m/n
    # Broadcast self.gamma ** (n - m) with appropriate masking to set values where n < m to 0
    D = (self.gamma ** (abs(n - m) // denominator) ) .float() # BiRetention
    # fill the NaN with 0
    D[D != D] = 0
    return D

In [14]:
sequence_length = 97
image_patches_length = 736
n = torch.arange(sequence_length).unsqueeze(1) # 
m = torch.arange(image_patches_length).unsqueeze(0)
denominator = m/n

In [20]:
# Calculate the scale factor for direct scaling of 'n' to 'm'
scale_factor = (image_patches_length - 1) / (sequence_length - 1)

# Scale 'n' indices directly to 'm' space
n_scaled_direct = torch.arange(sequence_length).float() * scale_factor

# Calculate the distance using the directly scaled 'n' and the original 'm' indices
distance_direct_scaled = abs(n_scaled_direct.unsqueeze(1) - torch.arange(image_patches_length).float())

# Check the first and last distances
first_distance = distance_direct_scaled[0, -1]
last_distance = distance_direct_scaled[-1, -1]

first_distance, last_distance, distance_direct_scaled


(tensor(735.),
 tensor(0.),
 tensor([[  0.0000,   1.0000,   2.0000,  ..., 733.0000, 734.0000, 735.0000],
         [  7.6562,   6.6562,   5.6562,  ..., 725.3438, 726.3438, 727.3438],
         [ 15.3125,  14.3125,  13.3125,  ..., 717.6875, 718.6875, 719.6875],
         ...,
         [719.6875, 718.6875, 717.6875,  ...,  13.3125,  14.3125,  15.3125],
         [727.3438, 726.3438, 725.3438,  ...,   5.6562,   6.6562,   7.6562],
         [735.0000, 734.0000, 733.0000,  ...,   2.0000,   1.0000,   0.0000]]))

In [24]:

# Calculate the scale factor for direct scaling of 'n' to 'm'
scale_factor = (image_patches_length - 1) / (sequence_length - 1)

# Scale 'n' indices directly to 'm' space
n_scaled_direct = torch.arange(sequence_length).float() * scale_factor

# Calculate the distance using the directly scaled 'n' and the original 'm' indices
distance_direct_scaled = abs(n_scaled_direct.unsqueeze(1) - torch.arange(image_patches_length).float())
# Normalize the distances to fit within the range of 0 to sequence_length - 1
distance_normalized = distance_direct_scaled * (sequence_length - 1) / (image_patches_length - 1)

# Check the first and last normalized distances
first_distance_normalized = distance_normalized[0, -1]
last_distance_normalized = distance_normalized[-1, -1]

first_distance_normalized, last_distance_normalized, distance_normalized


(tensor(96.),
 tensor(0.),
 tensor([[ 0.0000,  0.1306,  0.2612,  ..., 95.7388, 95.8694, 96.0000],
         [ 1.0000,  0.8694,  0.7388,  ..., 94.7388, 94.8694, 95.0000],
         [ 2.0000,  1.8694,  1.7388,  ..., 93.7388, 93.8694, 94.0000],
         ...,
         [94.0000, 93.8694, 93.7388,  ...,  1.7388,  1.8694,  2.0000],
         [95.0000, 94.8694, 94.7388,  ...,  0.7388,  0.8694,  1.0000],
         [96.0000, 95.8694, 95.7388,  ...,  0.2612,  0.1306,  0.0000]]))

In [26]:
first_distance_normalized

tensor(96.)

In [25]:
distance_normalized.shape

torch.Size([97, 736])

In [21]:
distance_direct_scaled.shape

torch.Size([97, 736])

In [17]:
m.shape

torch.Size([1, 736])

In [15]:
denominator

tensor([[       nan,        inf,        inf,  ...,        inf,        inf,
                inf],
        [0.0000e+00, 1.0000e+00, 2.0000e+00,  ..., 7.3300e+02, 7.3400e+02,
         7.3500e+02],
        [0.0000e+00, 5.0000e-01, 1.0000e+00,  ..., 3.6650e+02, 3.6700e+02,
         3.6750e+02],
        ...,
        [0.0000e+00, 1.0638e-02, 2.1277e-02,  ..., 7.7979e+00, 7.8085e+00,
         7.8191e+00],
        [0.0000e+00, 1.0526e-02, 2.1053e-02,  ..., 7.7158e+00, 7.7263e+00,
         7.7368e+00],
        [0.0000e+00, 1.0417e-02, 2.0833e-02,  ..., 7.6354e+00, 7.6458e+00,
         7.6562e+00]])

In [7]:
sequence_length = 97
image_patches_length = 736
n = torch.arange(sequence_length).unsqueeze(1) # 
m = torch.arange(image_patches_length).unsqueeze(0)

In [18]:
distance = abs(n - m)

tensor([[  0,   1,   2,  ..., 733, 734, 735],
        [  1,   0,   1,  ..., 732, 733, 734],
        [  2,   1,   0,  ..., 731, 732, 733],
        ...,
        [ 94,  93,  92,  ..., 639, 640, 641],
        [ 95,  94,  93,  ..., 638, 639, 640],
        [ 96,  95,  94,  ..., 637, 638, 639]])

In [ ]:
from this distance matrix, I want to scale it, because 2 sequences are differnet length, It should be aligned relatively. how Can I modify it? 

In [19]:
(abs(n - m) // denominator)

tensor([[       nan, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [       inf, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [       inf, 2.0000e+00, 0.0000e+00,  ..., 1.0000e+00, 1.0000e+00,
         1.0000e+00],
        ...,
        [       inf, 8.7420e+03, 4.3240e+03,  ..., 8.1000e+01, 8.1000e+01,
         8.1000e+01],
        [       inf, 8.9290e+03, 4.4170e+03,  ..., 8.2000e+01, 8.2000e+01,
         8.2000e+01],
        [       inf, 9.1190e+03, 4.5110e+03,  ..., 8.3000e+01, 8.3000e+01,
         8.3000e+01]])

In [9]:
abs(n - m)

tensor([[  0,   1,   2,  ..., 733, 734, 735],
        [  1,   0,   1,  ..., 732, 733, 734],
        [  2,   1,   0,  ..., 731, 732, 733],
        ...,
        [ 94,  93,  92,  ..., 639, 640, 641],
        [ 95,  94,  93,  ..., 638, 639, 640],
        [ 96,  95,  94,  ..., 637, 638, 639]])

In [8]:
(abs(n - m) // denominator)


tensor([[ 0.,  0.,  0.,  ..., 96., 96., 96.],
        [ 0.,  0.,  0.,  ..., 96., 96., 96.],
        [ 0.,  0.,  0.,  ..., 96., 96., 96.],
        ...,
        [12., 12., 12.,  ..., 84., 84., 84.],
        [12., 12., 12.,  ..., 84., 84., 84.],
        [12., 12., 12.,  ..., 83., 84., 84.]])

In [13]:
(abs(n - m) // denominator)[0]


tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,
         3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,
         5.,  5.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,
         7.,  7.,  7.,  7.,  7.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  9.,
         9.,  9.,  9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10.,
        11., 11., 11., 11., 11., 11., 11., 11., 12., 12., 12., 12., 12., 12.,
        12., 13., 13., 13., 13., 13., 13., 13., 13., 14., 14., 14., 14., 14.,
        14., 14., 15., 15., 15., 15., 15., 15., 15., 15., 16., 16., 16., 16.,
        16., 16., 16., 17., 17., 17., 17., 17., 17., 17., 17., 18., 18., 18.,
        18., 18., 18., 18., 18., 19., 19., 19., 19., 19., 19., 19., 20., 20.,
        20., 20., 20., 20., 20., 20., 21., 21., 21., 21., 21., 21., 21., 22.,
        22., 22., 22., 22., 22., 22., 22., 23., 23., 23., 23., 2

In [12]:
(abs(n - m) // denominator)[96]

tensor([12., 12., 12., 12., 12., 11., 11., 11., 11., 11., 11., 11., 11., 10.,
        10., 10., 10., 10., 10., 10., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
         8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  7.,  7.,  7.,  7.,  7.,  7.,
         7.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  5.,  5.,  5.,  5.,  5.,
         5.,  5.,  5.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  3.,  3.,  3.,  3.,
         3.,  3.,  3.,  3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
         3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,
         5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,  7.,  7.,
         7.,  7.,  7.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  9.,  9.,  9.,
         9.,  9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 1